[build]
  publish = ".next"
  command = "npm run build"
  [build.environment]
    NPM_FLAGS="--legacy-peer-deps"

[[redirects]]
  from="/"
  to="/de"
  status=302
  force=true
  conditions={Language = ["de"]}

[[redirects]]
  from="/"
  to="/en"
  status=302
  force=true
