name: Push main to prod
on: workflow_dispatch
permissions:
  contents: write
jobs:
  push-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # this means that it is a full history clone, not a shallow one
          # heroku push fails with a shallow clone
          fetch-depth: 0
      - name: git push
        run: |
          git push -f origin main:prod
